DELETE FROM `CHATS`;
DELETE FROM `USERS`;

INSERT INTO `USERS` (`ID`, `EMAIL`, `PASSWORD`, `ROLE`) VALUES 
(1, 'customer@test.com', '$2a$10$Y5KWtorVwUbuE.FraqTBD.hJIT7CcfgFNd7C./u.5N6BkScPF3ipq', 'CUSTOMER'),
(2, 'agent1@ycyw.com', '$2a$10$AiNQzm8AgoUr/JeA7GSUTe3FMZ9nCnXV1R12ZlDZF0K/q.YtqdAEK', 'CUSTOMER_SERVICE');

INSERT INTO `CHATS` (`CUSTOMER_ID`) VALUES 
(1);