CREATE TABLE IF NOT EXISTS `USERS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    `email` VARCHAR(255) NOT NULL UNIQUE, 
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('CUSTOMER', 'CUSTOMER_SERVICE') NOT NULL DEFAULT 'CUSTOMER'
);

CREATE TABLE IF NOT EXISTS `CHATS`(
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `customer_id` BIGINT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);