CREATE TABLE IF NOT EXISTS `USERS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    `first_name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE, 
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('CUSTOMER', 'CUSTOMER_SERVICE') NOT NULL DEFAULT 'CUSTOMER'
);

CREATE TABLE IF NOT EXISTS `CHATS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `customer_id` BIGINT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`customer_id`) REFERENCES `USERS` (`id`)
);

CREATE TABLE IF NOT EXISTS `MESSAGES` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `chat_id` BIGINT NOT NULL,
    `sender_id` BIGINT NOT NULL, 
    `content` TEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`chat_id`) REFERENCES `CHATS` (`id`),
    FOREIGN KEY (`sender_id`) REFERENCES `USERS` (`id`)
);