DELETE FROM `MESSAGES`;
DELETE FROM `CHATS`;
DELETE FROM `USERS`;

INSERT INTO `USERS` (`ID`, `FIRST_NAME`, `LAST_NAME`, `EMAIL`, `PASSWORD`, `ROLE`) VALUES 
(1, 'Anna', 'Rees', 'customer@test.com', '$2a$10$Y5KWtorVwUbuE.FraqTBD.hJIT7CcfgFNd7C./u.5N6BkScPF3ipq', 'CUSTOMER'),
(2, 'Eric', 'Lambert', 'agent1@ycyw.com', '$2a$10$AiNQzm8AgoUr/JeA7GSUTe3FMZ9nCnXV1R12ZlDZF0K/q.YtqdAEK', 'SUPPORT');

INSERT INTO `CHATS` (`ID`, `CUSTOMER_ID`, `STATUS`, `CREATED_AT`) VALUES
(1, 1, 'PENDING', CURRENT_TIMESTAMP);

INSERT INTO `MESSAGES` (`ID`, `CHAT_ID`, `SENDER_ID`, `CONTENT`, `CREATED_AT`) VALUES
(1, 1, 1, 'Hello, can you help me?', CURRENT_TIMESTAMP);
