CREATE TABLE IF NOT EXISTS `USERS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    `first_name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE, 
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('CUSTOMER', 'SUPPORT') NOT NULL DEFAULT 'CUSTOMER'
);

CREATE TABLE IF NOT EXISTS `ADDRESSES` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `street` VARCHAR(255) NOT NULL,
    `city` VARCHAR(255) NOT NULL,
    `state` VARCHAR(255),
    `postal_code` VARCHAR(20) NOT NULL,
    `country` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `CUSTOMERS` (
    `id` BIGINT NOT NULL PRIMARY KEY,
    `birth_date` DATE NOT NULL,
    `address_id` BIGINT NOT NULL,
    FOREIGN KEY (`id`) REFERENCES `USERS` (`id`),
    FOREIGN KEY (`address_id`) REFERENCES `ADDRESSES` (`id`)
);

CREATE TABLE IF NOT EXISTS `SUPPORT_AGENTS` (
    `id` BIGINT NOT NULL PRIMARY KEY,
    `hire_date` DATE NOT NULL,
    FOREIGN KEY (`id`) REFERENCES `USERS` (`id`)
);

CREATE TABLE IF NOT EXISTS `RENTAL_AGENCIES` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL, 
    `address_id` BIGINT NOT NULL, 
    `phone_number` VARCHAR(20) NOT NULL,
    FOREIGN KEY (`address_id`) REFERENCES `ADDRESSES` (`id`)
);

CREATE TABLE IF NOT EXISTS `CARS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `code` CHAR(4) NOT NULL, 
    `description` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `RENTAL_OFFERS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `pickup_date` DATETIME NOT NULL, 
    `return_date` DATETIME NOT NULL, 
    `price` DECIMAL(10, 2) NOT NULL, 
    `pickup_agency_id` BIGINT NOT NULL, 
    `return_agency_id` BIGINT NOT NULL,
    `car_id` BIGINT NOT NULL, 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `updated_at` TIMESTAMP,
    FOREIGN KEY (`pickup_agency_id`) REFERENCES `RENTAL_AGENCIES` (`id`),
    FOREIGN KEY (`return_agency_id`) REFERENCES `RENTAL_AGENCIES` (`id`), 
    FOREIGN KEY (`car_id`) REFERENCES `CARS` (`id`) 
);

CREATE TABLE IF NOT EXISTS `PAYMENTS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    `amount` DECIMAL(10, 2) NOT NULL, 
    `transaction_id` VARCHAR(255) NOT NULL, 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `BOOKINGS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    `status` ENUM('PAID', 'CANCELLED') NOT NULL, 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `updated_at` TIMESTAMP, 
    `rental_offer_id` BIGINT NOT NULL, 
    `customer_id` BIGINT NOT NULL, 
    `payment_id` BIGINT NOT NULL, 
    `refund_id` BIGINT, 
    FOREIGN KEY (`rental_offer_id`) REFERENCES `RENTAL_OFFERS` (`id`), 
    FOREIGN KEY (`customer_id`) REFERENCES `CUSTOMERS` (`id`), 
    FOREIGN KEY (`payment_id`) REFERENCES `PAYMENTS` (`id`),
    FOREIGN KEY (`refund_id`) REFERENCES `PAYMENTS` (`id`)
);

CREATE TABLE IF NOT EXISTS `CHATS` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `customer_id` BIGINT NOT NULL,
    `agent_id` BIGINT,
    `status` ENUM('PENDING', 'ACTIVE', 'CLOSED') NOT NULL, 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`customer_id`) REFERENCES `CUSTOMERS` (`id`), 
    FOREIGN KEY (`agent_id`) REFERENCES `SUPPORT_AGENTS` (`id`)
);

CREATE TABLE IF NOT EXISTS `MESSAGES` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `chat_id` BIGINT NOT NULL,
    `sender_id` BIGINT NOT NULL, 
    `content` TEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`chat_id`) REFERENCES `CHATS` (`id`),
    FOREIGN KEY (`sender_id`) REFERENCES `USERS` (`id`)
);